// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byte_dict.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_byte_5fdict_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_byte_5fdict_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_byte_5fdict_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_byte_5fdict_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_byte_5fdict_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_byte_5fdict_2eproto_metadata_getter(int index);
namespace VRProto {
class ByteDict;
struct ByteDictDefaultTypeInternal;
extern ByteDictDefaultTypeInternal _ByteDict_default_instance_;
class ByteDict_EntriesEntry_DoNotUse;
struct ByteDict_EntriesEntry_DoNotUseDefaultTypeInternal;
extern ByteDict_EntriesEntry_DoNotUseDefaultTypeInternal _ByteDict_EntriesEntry_DoNotUse_default_instance_;
}  // namespace VRProto
PROTOBUF_NAMESPACE_OPEN
template<> ::VRProto::ByteDict* Arena::CreateMaybeMessage<::VRProto::ByteDict>(Arena*);
template<> ::VRProto::ByteDict_EntriesEntry_DoNotUse* Arena::CreateMaybeMessage<::VRProto::ByteDict_EntriesEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace VRProto {

// ===================================================================

class ByteDict_EntriesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ByteDict_EntriesEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::uint32, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ByteDict_EntriesEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::uint32, float,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> SuperType;
  ByteDict_EntriesEntry_DoNotUse();
  explicit constexpr ByteDict_EntriesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit ByteDict_EntriesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const ByteDict_EntriesEntry_DoNotUse& other);
  static const ByteDict_EntriesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ByteDict_EntriesEntry_DoNotUse*>(&_ByteDict_EntriesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_byte_5fdict_2eproto);
    return ::descriptor_table_byte_5fdict_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class ByteDict PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VRProto.ByteDict) */ {
 public:
  inline ByteDict() : ByteDict(nullptr) {}
  virtual ~ByteDict();
  explicit constexpr ByteDict(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ByteDict(const ByteDict& from);
  ByteDict(ByteDict&& from) noexcept
    : ByteDict() {
    *this = ::std::move(from);
  }

  inline ByteDict& operator=(const ByteDict& from) {
    CopyFrom(from);
    return *this;
  }
  inline ByteDict& operator=(ByteDict&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ByteDict& default_instance() {
    return *internal_default_instance();
  }
  static inline const ByteDict* internal_default_instance() {
    return reinterpret_cast<const ByteDict*>(
               &_ByteDict_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ByteDict& a, ByteDict& b) {
    a.Swap(&b);
  }
  inline void Swap(ByteDict* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ByteDict* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ByteDict* New() const final {
    return CreateMaybeMessage<ByteDict>(nullptr);
  }

  ByteDict* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ByteDict>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ByteDict& from);
  void MergeFrom(const ByteDict& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ByteDict* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VRProto.ByteDict";
  }
  protected:
  explicit ByteDict(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_byte_5fdict_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 1,
  };
  // map<uint32, float> entries = 1;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >&
      _internal_entries() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >*
      _internal_mutable_entries();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >&
      entries() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >*
      mutable_entries();

  // @@protoc_insertion_point(class_scope:VRProto.ByteDict)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      ByteDict_EntriesEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::uint32, float,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT> entries_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_byte_5fdict_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ByteDict

// map<uint32, float> entries = 1;
inline int ByteDict::_internal_entries_size() const {
  return entries_.size();
}
inline int ByteDict::entries_size() const {
  return _internal_entries_size();
}
inline void ByteDict::clear_entries() {
  entries_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >&
ByteDict::_internal_entries() const {
  return entries_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >&
ByteDict::entries() const {
  // @@protoc_insertion_point(field_map:VRProto.ByteDict.entries)
  return _internal_entries();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >*
ByteDict::_internal_mutable_entries() {
  return entries_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::uint32, float >*
ByteDict::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_map:VRProto.ByteDict.entries)
  return _internal_mutable_entries();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace VRProto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_byte_5fdict_2eproto
