// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_controller_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_controller_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "byte_dict.pb.h"
#include "pose.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_controller_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_controller_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_controller_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_controller_2eproto_metadata_getter(int index);
namespace VRProto {
class Controller;
struct ControllerDefaultTypeInternal;
extern ControllerDefaultTypeInternal _Controller_default_instance_;
}  // namespace VRProto
PROTOBUF_NAMESPACE_OPEN
template<> ::VRProto::Controller* Arena::CreateMaybeMessage<::VRProto::Controller>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace VRProto {

// ===================================================================

class Controller PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VRProto.Controller) */ {
 public:
  inline Controller() : Controller(nullptr) {}
  virtual ~Controller();
  explicit constexpr Controller(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Controller(const Controller& from);
  Controller(Controller&& from) noexcept
    : Controller() {
    *this = ::std::move(from);
  }

  inline Controller& operator=(const Controller& from) {
    CopyFrom(from);
    return *this;
  }
  inline Controller& operator=(Controller&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Controller& default_instance() {
    return *internal_default_instance();
  }
  static inline const Controller* internal_default_instance() {
    return reinterpret_cast<const Controller*>(
               &_Controller_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Controller& a, Controller& b) {
    a.Swap(&b);
  }
  inline void Swap(Controller* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Controller* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Controller* New() const final {
    return CreateMaybeMessage<Controller>(nullptr);
  }

  Controller* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Controller>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Controller& from);
  void MergeFrom(const Controller& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Controller* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VRProto.Controller";
  }
  protected:
  explicit Controller(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_controller_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPoseFieldNumber = 1,
    kButtonsFieldNumber = 2,
  };
  // .VRProto.Pose pose = 1;
  bool has_pose() const;
  private:
  bool _internal_has_pose() const;
  public:
  void clear_pose();
  const ::VRProto::Pose& pose() const;
  ::VRProto::Pose* release_pose();
  ::VRProto::Pose* mutable_pose();
  void set_allocated_pose(::VRProto::Pose* pose);
  private:
  const ::VRProto::Pose& _internal_pose() const;
  ::VRProto::Pose* _internal_mutable_pose();
  public:
  void unsafe_arena_set_allocated_pose(
      ::VRProto::Pose* pose);
  ::VRProto::Pose* unsafe_arena_release_pose();

  // .VRProto.ByteDict buttons = 2;
  bool has_buttons() const;
  private:
  bool _internal_has_buttons() const;
  public:
  void clear_buttons();
  const ::VRProto::ByteDict& buttons() const;
  ::VRProto::ByteDict* release_buttons();
  ::VRProto::ByteDict* mutable_buttons();
  void set_allocated_buttons(::VRProto::ByteDict* buttons);
  private:
  const ::VRProto::ByteDict& _internal_buttons() const;
  ::VRProto::ByteDict* _internal_mutable_buttons();
  public:
  void unsafe_arena_set_allocated_buttons(
      ::VRProto::ByteDict* buttons);
  ::VRProto::ByteDict* unsafe_arena_release_buttons();

  // @@protoc_insertion_point(class_scope:VRProto.Controller)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::VRProto::Pose* pose_;
  ::VRProto::ByteDict* buttons_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_controller_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Controller

// .VRProto.Pose pose = 1;
inline bool Controller::_internal_has_pose() const {
  return this != internal_default_instance() && pose_ != nullptr;
}
inline bool Controller::has_pose() const {
  return _internal_has_pose();
}
inline const ::VRProto::Pose& Controller::_internal_pose() const {
  const ::VRProto::Pose* p = pose_;
  return p != nullptr ? *p : reinterpret_cast<const ::VRProto::Pose&>(
      ::VRProto::_Pose_default_instance_);
}
inline const ::VRProto::Pose& Controller::pose() const {
  // @@protoc_insertion_point(field_get:VRProto.Controller.pose)
  return _internal_pose();
}
inline void Controller::unsafe_arena_set_allocated_pose(
    ::VRProto::Pose* pose) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose_);
  }
  pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:VRProto.Controller.pose)
}
inline ::VRProto::Pose* Controller::release_pose() {
  
  ::VRProto::Pose* temp = pose_;
  pose_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::VRProto::Pose* Controller::unsafe_arena_release_pose() {
  // @@protoc_insertion_point(field_release:VRProto.Controller.pose)
  
  ::VRProto::Pose* temp = pose_;
  pose_ = nullptr;
  return temp;
}
inline ::VRProto::Pose* Controller::_internal_mutable_pose() {
  
  if (pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::VRProto::Pose>(GetArena());
    pose_ = p;
  }
  return pose_;
}
inline ::VRProto::Pose* Controller::mutable_pose() {
  // @@protoc_insertion_point(field_mutable:VRProto.Controller.pose)
  return _internal_mutable_pose();
}
inline void Controller::set_allocated_pose(::VRProto::Pose* pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose_);
  }
  if (pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose)->GetArena();
    if (message_arena != submessage_arena) {
      pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:VRProto.Controller.pose)
}

// .VRProto.ByteDict buttons = 2;
inline bool Controller::_internal_has_buttons() const {
  return this != internal_default_instance() && buttons_ != nullptr;
}
inline bool Controller::has_buttons() const {
  return _internal_has_buttons();
}
inline const ::VRProto::ByteDict& Controller::_internal_buttons() const {
  const ::VRProto::ByteDict* p = buttons_;
  return p != nullptr ? *p : reinterpret_cast<const ::VRProto::ByteDict&>(
      ::VRProto::_ByteDict_default_instance_);
}
inline const ::VRProto::ByteDict& Controller::buttons() const {
  // @@protoc_insertion_point(field_get:VRProto.Controller.buttons)
  return _internal_buttons();
}
inline void Controller::unsafe_arena_set_allocated_buttons(
    ::VRProto::ByteDict* buttons) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(buttons_);
  }
  buttons_ = buttons;
  if (buttons) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:VRProto.Controller.buttons)
}
inline ::VRProto::ByteDict* Controller::release_buttons() {
  
  ::VRProto::ByteDict* temp = buttons_;
  buttons_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::VRProto::ByteDict* Controller::unsafe_arena_release_buttons() {
  // @@protoc_insertion_point(field_release:VRProto.Controller.buttons)
  
  ::VRProto::ByteDict* temp = buttons_;
  buttons_ = nullptr;
  return temp;
}
inline ::VRProto::ByteDict* Controller::_internal_mutable_buttons() {
  
  if (buttons_ == nullptr) {
    auto* p = CreateMaybeMessage<::VRProto::ByteDict>(GetArena());
    buttons_ = p;
  }
  return buttons_;
}
inline ::VRProto::ByteDict* Controller::mutable_buttons() {
  // @@protoc_insertion_point(field_mutable:VRProto.Controller.buttons)
  return _internal_mutable_buttons();
}
inline void Controller::set_allocated_buttons(::VRProto::ByteDict* buttons) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(buttons_);
  }
  if (buttons) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(buttons)->GetArena();
    if (message_arena != submessage_arena) {
      buttons = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, buttons, submessage_arena);
    }
    
  } else {
    
  }
  buttons_ = buttons;
  // @@protoc_insertion_point(field_set_allocated:VRProto.Controller.buttons)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace VRProto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_controller_2eproto
