# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ByteDict(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsByteDict(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ByteDict()
        x.Init(buf, n + offset)
        return x

    # ByteDict
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ByteDict
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from fbs.ByteDictEntry import ByteDictEntry
            obj = ByteDictEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ByteDict
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ByteDict
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ByteDictStart(builder): builder.StartObject(1)
def ByteDictAddEntries(builder, entries): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)
def ByteDictStartEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ByteDictEnd(builder): return builder.EndObject()
